from __future__ import annotations

import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from etl.chatbot import SUGGESTED_PROMPTS, answer_query
from etl.live_market import fetch_intraday, fetch_live_board, fetch_yahoo_quote, verify_quote
from etl.technicals import technical_snapshot, technicals
from etl.news_sources import NEWS_SOURCES

ROOT = Path(__file__).resolve().parent
DB_PATH = ROOT / "data" / "processed" / "company_intelligence.db"
IST = ZoneInfo("Asia/Kolkata")

st.set_page_config(
    page_title="India Company Intelligence Pro",
    page_icon="🇮🇳",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
<style>
:root { --navy:#0f172a; --slate:#475569; --muted:#64748b; --line:#e2e8f0; }
.block-container { padding-top: 1.0rem; padding-bottom: 3rem; max-width: 1500px; }
.hero { padding: 8px 0 12px 0; }
.eyebrow { color:#0f766e; font-weight:700; font-size:.82rem; letter-spacing:.08em; text-transform:uppercase; }
.hero h1 { margin: 2px 0 5px 0; color:var(--navy); font-size:2.5rem; }
.hero p { color:var(--slate); margin:0; font-size:1rem; }
.live-pill { display:inline-block; padding:5px 9px; border-radius:999px; font-weight:700; font-size:.78rem; margin-top:8px; border:1px solid #bbf7d0; background:#f0fdf4; color:#166534; }
.card { border:1px solid var(--line); border-radius:16px; padding:14px 16px; background:#fff; }
.metric-label { color:var(--muted); font-size:.80rem; }
.metric-value { color:var(--navy); font-size:1.55rem; font-weight:750; margin-top:2px; }
.metric-delta { font-size:.80rem; margin-top:3px; }
.positive { color:#047857; }
.negative { color:#b91c1c; }
.neutral { color:#475569; }
.source-chip { display:inline-block; padding:4px 8px; border:1px solid var(--line); border-radius:999px; margin-right:4px; margin-bottom:5px; font-size:.75rem; color:#334155; background:#f8fafc; }
</style>
""",
    unsafe_allow_html=True,
)


def connect() -> sqlite3.Connection:
    return sqlite3.connect(DB_PATH)


def q(sql: str, params=()) -> pd.DataFrame:
    with connect() as conn:
        return pd.read_sql_query(sql, conn, params=params)


@st.cache_data(ttl=300)
def load_all():
    companies = q("SELECT * FROM company_master")
    prices = q("SELECT * FROM price_daily ORDER BY trade_date")
    financials = q("SELECT * FROM financial_snapshot ORDER BY as_of_date DESC")
    news = q("SELECT * FROM news_articles ORDER BY published_at DESC")
    # Backward compatibility with databases generated by v1 of the project.
    if "aliases" not in companies.columns:
        companies["aliases"] = ""
    for col, default in {
        "source": "Unknown", "company_name": "", "summary": "", "sentiment": "Neutral",
        "event_type": "General Market", "coverage_count": 1, "corroboration": "Single source"
    }.items():
        if col not in news.columns:
            news[col] = default
    logs = q("SELECT * FROM etl_run_log ORDER BY run_ts_utc DESC")
    return companies, prices, financials, news, logs


@st.cache_data(ttl=12, show_spinner=False)
def live_quote(ticker: str) -> dict:
    try:
        quote = fetch_yahoo_quote(ticker)
    except Exception as exc:
        quote = {
            "ticker": ticker,
            "source": "Yahoo Finance / yfinance",
            "status": f"ERROR: {type(exc).__name__}",
            "price": None,
        }

    # If live provider fails, use the latest stored market record.
    if quote.get("price") is None:
        try:
            hist = q(
                "SELECT * FROM price_daily WHERE ticker=? ORDER BY trade_date DESC LIMIT 2",
                (ticker,),
            )
            if not hist.empty:
                latest = hist.iloc[0]
                price = float(latest["close"])
                prev = (
                    float(hist.iloc[1]["close"])
                    if len(hist) > 1 and pd.notna(hist.iloc[1]["close"])
                    else None
                )
                change = price - prev if prev else None
                pct_change = (change / prev * 100) if prev else None

                return {
                    "ticker": ticker,
                    "source": "Scheduled ETL (cached close)",
                    "status": "CACHED",
                    "price": price,
                    "previous_close": prev,
                    "change": change,
                    "pct_change": pct_change,
                    "day_high": None,
                    "day_low": None,
                    "volume": (
                        float(latest["volume"])
                        if "volume" in latest.index and pd.notna(latest["volume"])
                        else None
                    ),
                    "timestamp_utc": f"{latest['trade_date']}T00:00:00+00:00",
                }
        except Exception:
            pass

    return quote


@st.cache_data(ttl=20, show_spinner=False)
def live_board(tickers: tuple[str, ...]) -> pd.DataFrame:
    try:
        return fetch_live_board(list(tickers))
    except Exception:
        return pd.DataFrame()


@st.cache_data(ttl=20, show_spinner=False)
def intraday_chart(ticker: str, period: str = "1d", interval: str = "1m") -> pd.DataFrame:
    try:
        return fetch_intraday(ticker, period=period, interval=interval)
    except Exception:
        return pd.DataFrame()


@st.cache_data(ttl=45, show_spinner=False)
def quote_verification(ticker: str) -> dict:
    try:
        return verify_quote(ticker)
    except Exception as exc:
        return {"verdict": "ERROR", "error": f"{type(exc).__name__}: {exc}"}


def pct(x) -> str:
    return "—" if pd.isna(x) else f"{float(x):,.1f}%"


def money_ind(x) -> str:
    if pd.isna(x):
        return "—"
    x = float(x)
    if abs(x) >= 1e12:
        return f"₹{x/1e12:.2f}T"
    if abs(x) >= 1e9:
        return f"₹{x/1e9:.1f}B"
    if abs(x) >= 1e6:
        return f"₹{x/1e6:.1f}M"
    return f"₹{x:,.0f}"


def india_now() -> datetime:
    return datetime.now(timezone.utc).astimezone(IST)


def attention_score(companies, prices, financials, news) -> pd.DataFrame:
    latest = prices.sort_values("trade_date").groupby("ticker").tail(1).copy()
    f = financials.sort_values("as_of_date").groupby("ticker").tail(1).copy()
    out = latest.merge(
        companies[["ticker", "company_name", "sector", "industry"]], on="ticker", how="left"
    )
    out = out.merge(
        f[["ticker", "revenue", "revenue_growth_pct", "profit_growth_pct", "net_margin_pct", "debt_equity", "roe_pct"]],
        on="ticker",
        how="left",
    )
    out["financial_pressure_score"] = (
        (out["revenue_growth_pct"] < 0).astype(int)
        + (out["profit_growth_pct"] < 0).astype(int)
        + ((out["debt_equity"] > 2).fillna(False)).astype(int)
    )
    now = pd.Timestamp.now(tz="UTC")
    n = news.copy()
    if "coverage_count" not in n.columns:
        n["coverage_count"] = 1
    if not n.empty:
        n["published_at_dt"] = pd.to_datetime(n["published_at"], errors="coerce", utc=True)
        recent = n[n["published_at_dt"] >= now - pd.Timedelta(days=7)].groupby("ticker").agg(
            news_7d=("guid", "count"),
            corroborated_7d=("coverage_count", lambda s: int((s.fillna(1) >= 2).sum())),
        )
        prior = n[(n["published_at_dt"] >= now - pd.Timedelta(days=14)) & (n["published_at_dt"] < now - pd.Timedelta(days=7))].groupby("ticker").size().rename("news_prev_7d")
        n2 = recent.join(prior, how="outer").fillna(0).reset_index()
    else:
        n2 = pd.DataFrame(columns=["ticker", "news_7d", "corroborated_7d", "news_prev_7d"])
    out = out.merge(n2, on="ticker", how="left").fillna({"news_7d": 0, "corroborated_7d": 0, "news_prev_7d": 0})
    out["news_spike_score"] = ((out["news_7d"] >= 3) & (out["news_7d"] >= out["news_prev_7d"].replace(0, 1) * 1.5)).astype(int)
    out["corroboration_score"] = (out["corroborated_7d"] >= 2).astype(int)
    out["attention_score"] = out["market_score"].fillna(0) + out["financial_pressure_score"] + out["news_spike_score"] + out["corroboration_score"]
    out["attention_flag"] = np.select(
        [out["attention_score"] >= 5, out["attention_score"] >= 3],
        ["HIGH", "MEDIUM"],
        default="LOW",
    )
    out["constructive_signal"] = ((out["return_30d"] > 5) & (out["profit_growth_pct"] > 0)).fillna(False)
    return out.sort_values(["attention_score", "return_30d"], ascending=[False, True])


def render_stock_volume(ticker: str, company_name: str):
    st.subheader(f"📈 {company_name} — separate stock and volume tracking")
    c1, c2, c3 = st.columns(3)
    with c1:
        period = st.selectbox("Price period", ["1d", "5d", "1mo", "3mo"], index=2, key=f"sv_period_{ticker}")
    with c2:
        interval = st.selectbox("Chart interval", ["1m", "5m", "15m", "30m", "1h", "1d"], index=1, key=f"sv_interval_{ticker}")
    with c3:
        st.caption("Use 1m–30m for intraday activity; 1h/1d for broader trend context.")
    raw = intraday_chart(ticker, period=period, interval=interval)
    if raw.empty:
        st.warning("No intraday data is available for this ticker/timeframe right now.")
        return
    tech = technicals(raw)
    snap = technical_snapshot(tech)

    k1, k2, k3, k4, k5 = st.columns(5)
    k1.metric("Latest chart price", f"₹{snap['close']:,.2f}")
    k2.metric("RSI 14", f"{snap['rsi']:.1f}" if pd.notna(snap['rsi']) else "—")
    k3.metric("Relative volume", f"{snap['relative_volume']:.2f}x" if pd.notna(snap['relative_volume']) else "—")
    k4.metric("ATR 14", f"₹{snap['atr14']:,.2f}" if pd.notna(snap['atr14']) else "—")
    k5.metric("Technical read", snap["read"])

    st.markdown("#### Stock price — candlestick + trend overlays")
    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=tech["Datetime"], open=tech["open"], high=tech["high"], low=tech["low"], close=tech["close"], name="OHLC"
    ))
    for col, name in [("sma20", "SMA 20"), ("sma50", "SMA 50"), ("bb_upper", "Bollinger Upper"), ("bb_lower", "Bollinger Lower")]:
        fig.add_trace(go.Scatter(x=tech["Datetime"], y=tech[col], name=name, mode="lines", line=dict(dash="dot") if "bb" in col else None))
    fig.update_layout(height=520, hovermode="x unified", xaxis_rangeslider_visible=False, title=f"{company_name} price action")
    st.plotly_chart(fig, use_container_width=True, key=f"stock_chart_{ticker}_{period}_{interval}")

    st.markdown("#### Volume — dedicated chart")
    vf = go.Figure()
    vf.add_trace(go.Bar(x=tech["Datetime"], y=tech["volume"], name="Traded volume"))
    vf.add_trace(go.Scatter(x=tech["Datetime"], y=tech["volume_sma20"], name="20-period avg volume", mode="lines"))
    vf.update_layout(height=300, hovermode="x unified", title="Volume and activity")
    st.plotly_chart(vf, use_container_width=True, key=f"volume_chart_{ticker}_{period}_{interval}")


def render_graphical_analysis(tech: pd.DataFrame):
    if tech.empty:
        st.info("Technical graphs are unavailable for this timeframe.")
        return
    snap = technical_snapshot(tech)
    a, b = st.columns(2)
    with a:
        fig = go.Figure(go.Indicator(
            mode="gauge+number", value=float(snap["rsi"]) if pd.notna(snap["rsi"]) else 50,
            title={"text": "RSI 14"}, gauge={"axis": {"range": [0, 100]}, "steps": [{"range": [0, 30]}, {"range": [30, 70]}, {"range": [70, 100]}], "threshold": {"value": 50, "line": {"width": 4}}}
        ))
        fig.update_layout(height=280)
        st.plotly_chart(fig, use_container_width=True)
    with b:
        balance = snap["bull_votes"] - snap["bear_votes"]
        fig = go.Figure(go.Indicator(
            mode="gauge+number", value=balance, number={"suffix": " / 5"},
            title={"text": "Technical signal balance"}, gauge={"axis": {"range": [-5, 5]}, "threshold": {"value": 0, "line": {"width": 4}}}
        ))
        fig.update_layout(height=280)
        st.plotly_chart(fig, use_container_width=True)

    macd = go.Figure()
    macd.add_trace(go.Bar(x=tech["Datetime"], y=tech["macd_hist"], name="MACD histogram"))
    macd.add_trace(go.Scatter(x=tech["Datetime"], y=tech["macd"], name="MACD", mode="lines"))
    macd.add_trace(go.Scatter(x=tech["Datetime"], y=tech["macd_signal"], name="Signal", mode="lines"))
    macd.update_layout(height=340, title="MACD — graphical analysis", hovermode="x unified")
    st.plotly_chart(macd, use_container_width=True)

    rsi = go.Figure(go.Scatter(x=tech["Datetime"], y=tech["rsi14"], mode="lines", name="RSI 14"))
    rsi.add_hline(y=70, line_dash="dot")
    rsi.add_hline(y=30, line_dash="dot")
    rsi.update_layout(height=320, title="RSI trend", yaxis_range=[0, 100], hovermode="x unified")
    st.plotly_chart(rsi, use_container_width=True)

    numbers = pd.DataFrame([
        ["Latest price", snap["close"], "₹"], ["SMA 20", snap["sma20"], "₹"], ["SMA 50", snap["sma50"], "₹"],
        ["SMA 200", snap["sma200"], "₹"], ["RSI 14", snap["rsi"], ""], ["MACD", snap["macd"], ""],
        ["MACD signal", snap["macd_signal"], ""], ["ATR 14", snap["atr14"], "₹"], ["Relative volume", snap["relative_volume"], "x"],
    ], columns=["Metric", "Value", "Unit"])
    st.markdown("#### Technical numbers")
    st.dataframe(numbers.style.format({"Value": "{:.2f}"}), use_container_width=True, hide_index=True)


def render_chatbot(companies, scored, prices, financials, news):
    st.subheader("🤖 Analyst Copilot")
    st.caption("Ask the dashboard questions in plain English. Answers are grounded in the current company, market, financial and multi-source news data; no paid AI API key is required.")
    st.markdown("**Try:** " + " · ".join(SUGGESTED_PROMPTS))
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []
    for role, message in st.session_state.chat_history:
        with st.chat_message(role):
            st.markdown(message)
    prompt = st.chat_input("Ask: What is HDFC Bank's live price? Why is Reliance high attention?")
    if prompt:
        st.session_state.chat_history.append(("user", prompt))
        with st.chat_message("user"):
            st.markdown(prompt)
        with st.chat_message("assistant"):
            with st.spinner("Checking current dashboard data…"):
                response = answer_query(prompt, companies, scored, prices, financials, news, live_quote_fn=live_quote)
            st.markdown(response)
        st.session_state.chat_history.append(("assistant", response))
    if st.button("Clear chat", key="clear_chat"):
        st.session_state.chat_history = []
        st.rerun()


def analysis_narrative(c, news_count: int, corr: int) -> list[str]:
    points = []
    if pd.notna(c.get("return_30d")):
        points.append(f"30-day momentum is {c['return_30d']:.1f}%, with market stress score {int(c.get('market_score',0))}.")
    if pd.notna(c.get("volatility_30d")):
        points.append(f"Annualised 30-day volatility is {c['volatility_30d']:.1f}% and the 90-day drawdown is {c.get('max_drawdown_90d',np.nan):.1f}%.")
    if pd.notna(c.get("revenue_growth_pct")):
        points.append(f"Latest available revenue growth is {c['revenue_growth_pct']:.1f}% and profit growth is {c.get('profit_growth_pct',np.nan):.1f}%.")
    if news_count:
        extra = f"; {corr} corroborated clusters" if corr else ""
        points.append(f"The news layer found {news_count} headlines in the last 7 days{extra}.")
    points.append("Use the source-verification panel before treating any single market or news observation as confirmed.")
    return points


def render_live_pulse(universe: pd.DataFrame, companies: pd.DataFrame):
    st.subheader("⚡ Live Market Pulse")
    st.caption("Live quote layer refreshes while this session is active. Historical analytics remain based on the scheduled ETL dataset.")
    top_names = universe.sort_values("attention_score", ascending=False)["company_name"].head(8).tolist()
    live_company = st.selectbox("Live focus company", top_names, key="live_focus_company")
    ticker = companies.loc[companies["company_name"] == live_company, "ticker"].iloc[0]
    interval = st.select_slider("Refresh live quote every", options=[10, 20, 30, 60], value=20, format_func=lambda x: f"{x}s")
    start = st.checkbox("Auto-refresh live view", value=True)
    run_every = f"{interval}s" if start else None

    @st.fragment(run_every=run_every, key="live_pulse_fragment")
    def _live_fragment():
        quote = live_quote(ticker)
        last = quote.get("price")
        chg = quote.get("pct_change")
        status = quote.get("status", "UNKNOWN")
        ts = pd.to_datetime(quote.get("timestamp_utc"), utc=True, errors="coerce")
        ts_ist = ts.tz_convert(IST) if pd.notna(ts) else pd.Timestamp.now(tz=IST)
        col = "positive" if (chg or 0) > 0 else "negative" if (chg or 0) < 0 else "neutral"
        c1, c2, c3, c4, c5 = st.columns(5)
        c1.metric(live_company, f"₹{last:,.2f}" if last is not None else "—", f"{chg:.2f}%" if chg is not None else None)
        c2.metric("Day high", f"₹{quote['day_high']:,.2f}" if quote.get("day_high") is not None else "—")
        c3.metric("Day low", f"₹{quote['day_low']:,.2f}" if quote.get("day_low") is not None else "—")
        c4.metric("Volume", f"{quote['volume']:,.0f}" if quote.get("volume") is not None else "—")
        c5.metric("Feed", "OK" if status == "OK" else status)
        st.markdown(f'<span class="live-pill">● LIVE QUOTE • {ts_ist.strftime("%d %b %Y %H:%M:%S IST")} • Yahoo Finance / yfinance</span>', unsafe_allow_html=True)
        intr = intraday_chart(ticker)
        if not intr.empty:
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=intr["Datetime"], y=intr["Close"], name="Last traded price", mode="lines"))
            fig.update_layout(height=390, margin=dict(l=10,r=10,t=50,b=10), title="Intraday price", hovermode="x unified")
            st.plotly_chart(fig, use_container_width=True, key=f"live_intraday_{ticker}")
    _live_fragment()


def main():
    if not DB_PATH.exists():
        st.error("The database is missing. Run the scheduled ETL or initialize the repository first.")
        st.stop()

    companies, prices, financials, news, logs = load_all()
    scored = attention_score(companies, prices, financials, news)

    latest_date = prices["trade_date"].max() if not prices.empty else "—"
    last_run = logs.iloc[0] if not logs.empty else None
    demo = False
    if not financials.empty:
        demo = financials["source"].fillna("").str.contains("DEMO", case=False).all()

    st.markdown('<div class="hero"><div class="eyebrow">INDIA • LIVE MARKET INTELLIGENCE</div><h1>🇮🇳 India Company Intelligence Pro</h1><p>Live market tracking + multi-source verification + technical analysis + fundamentals + corroborated news.</p></div>', unsafe_allow_html=True)
    if demo:
        st.warning("The historical database still contains seed/demo records. Live quotes can still refresh separately. Run the GitHub ETL to refresh the historical layer.")
    if last_run is not None:
        st.caption(f"Historical ETL: {last_run['status']} • {last_run['run_ts_utc']} • latest stored market date: {latest_date}")

    st.sidebar.header("Control Center")
    sectors = sorted(companies["sector"].dropna().unique())
    sector_pick = st.sidebar.multiselect("Sector", sectors, default=sectors)
    names = companies.loc[companies["sector"].isin(sector_pick), "company_name"].sort_values().tolist()
    company_pick = st.sidebar.multiselect("Companies", names)
    min_score = st.sidebar.slider("Minimum attention score", 0, 10, 0)
    live_board_n = st.sidebar.slider("Live board size", 3, 10, 6)

    universe = scored[scored["sector"].isin(sector_pick)].copy()
    if company_pick:
        universe = universe[universe["company_name"].isin(company_pick)]
    universe = universe[universe["attention_score"] >= min_score]
    if universe.empty:
        st.info("No companies match the selected filters.")
        st.stop()

    k1, k2, k3, k4, k5, k6 = st.columns(6)
    k1.metric("Companies", len(universe))
    k2.metric("High attention", int((universe.attention_flag == "HIGH").sum()))
    k3.metric("Median 30D return", pct(universe.return_30d.median()))
    k4.metric("Avg. volatility", pct(universe.volatility_30d.mean()))
    k5.metric("News / 7D", int(universe.news_7d.sum()))
    k6.metric("Corroborated", int(universe.corroborated_7d.sum()))

    tabs = st.tabs([
        "⚡ Live Market", "📊 Stock & Volume", "📐 Technical Graphics", "🤖 Analyst Chat",
        "Executive Pulse", "Company Deep Dive", "Sector Intelligence", "News Intelligence", "Source Verification", "Data & SQL"
    ])

    with tabs[0]:
        render_live_pulse(universe, companies)
        st.divider()
        st.subheader("Live Watchlist")
        tickers = tuple(universe.sort_values("attention_score", ascending=False)["ticker"].head(live_board_n).tolist())
        start_board = st.checkbox("Auto-refresh watchlist", value=False, help="Use this when actively monitoring a small board; the quote feed refreshes while your session is open.")
        interval_board = st.select_slider("Watchlist refresh", options=[20, 30, 60], value=30, format_func=lambda x: f"every {x}s")
        run_board = f"{interval_board}s" if start_board else None

        @st.fragment(run_every=run_board, key="watchlist_fragment")
        def _watchlist_fragment():
            board = live_board(tickers)
            if board.empty:
                st.info("Live watchlist could not retrieve quotes right now. The historical layer remains available.")
                return
            board = board.merge(companies[["ticker", "company_name", "sector"]], on="ticker", how="left")
            board["Price"] = board["price"].map(lambda x: f"₹{x:,.2f}" if pd.notna(x) else "—")
            board["Change"] = board["pct_change"].map(lambda x: f"{x:+.2f}%" if pd.notna(x) else "—")
            view = board[["company_name", "sector", "Price", "Change", "day_high", "day_low", "volume", "status", "timestamp_utc"]].copy()
            view.columns = ["Company", "Sector", "Live Price", "Today", "Day High", "Day Low", "Volume", "Status", "Quote Timestamp"]
            st.dataframe(view, use_container_width=True, hide_index=True)
        _watchlist_fragment()

    with tabs[1]:
        company = st.selectbox("Company", universe["company_name"].tolist(), key="stock_volume_company")
        c = universe[universe["company_name"] == company].iloc[0]
        render_stock_volume(c["ticker"], company)

    with tabs[2]:
        company = st.selectbox("Technical company", universe["company_name"].tolist(), key="technical_company")
        c = universe[universe["company_name"] == company].iloc[0]
        period = st.selectbox("Analysis period", ["1mo", "3mo", "6mo", "1y"], index=1, key="technical_period")
        interval = "1h" if period in ["1mo", "3mo"] else "1d"
        hist = intraday_chart(c["ticker"], period=period, interval=interval)
        render_graphical_analysis(technicals(hist))

    with tabs[3]:
        render_chatbot(companies, universe, prices, financials, news)

    with tabs[4]:
        st.subheader("Where should an analyst look first?")
        left, right = st.columns([1.1, 1])
        with left:
            plot = universe.sort_values("attention_score", ascending=True)
            fig = px.bar(plot, x="attention_score", y="company_name", orientation="h", color="attention_flag", text="attention_score", title="Research attention queue")
            fig.update_layout(height=620, xaxis_title="Triage score", yaxis_title=None)
            st.plotly_chart(fig, use_container_width=True)
        with right:
            fig2 = px.scatter(universe, x="volatility_30d", y="return_30d", size="attention_score", color="sector", hover_name="company_name", custom_data=["attention_flag"], title="Risk / momentum map")
            fig2.add_vline(x=25, line_dash="dot")
            fig2.add_hline(y=0, line_dash="dot")
            fig2.update_layout(height=620, xaxis_title="30D annualised volatility (%)", yaxis_title="30D return (%)")
            st.plotly_chart(fig2, use_container_width=True)
        table = universe[["company_name","sector","return_30d","volatility_30d","max_drawdown_90d","revenue_growth_pct","profit_growth_pct","news_7d","corroborated_7d","attention_score","attention_flag"]].copy()
        table.columns = ["Company","Sector","30D Return %","Volatility %","90D Drawdown %","Revenue Growth %","Profit Growth %","News / 7D","Corroborated","Attention","Flag"]
        st.dataframe(table.round(2), use_container_width=True, hide_index=True)
        st.download_button("Download live watchlist snapshot", table.to_csv(index=False).encode("utf-8"), "india_company_watchlist.csv", "text/csv")

    with tabs[5]:
        company = st.selectbox("Company", universe["company_name"].tolist(), key="deep_company")
        c = universe[universe["company_name"] == company].iloc[0]
        r = companies[companies["ticker"] == c.ticker].iloc[0]
        p = prices[prices.ticker == c.ticker].sort_values("trade_date").copy()
        f = financials[financials.ticker == c.ticker].sort_values("as_of_date", ascending=False)
        nw = news[news.ticker == c.ticker].copy().head(40)

        qdata = live_quote(c.ticker)
        l1, l2, l3, l4, l5 = st.columns(5)
        l1.metric("Live / latest quote", f"₹{qdata['price']:,.2f}" if qdata.get("price") is not None else "—", f"{qdata['pct_change']:+.2f}%" if qdata.get("pct_change") is not None else None)
        l2.metric("30D return", pct(c.return_30d))
        l3.metric("Attention", f"{int(c.attention_score)} / {c.attention_flag}")
        l4.metric("Profit growth", pct(c.profit_growth_pct))
        l5.metric("News coverage", f"{int(c.news_7d)} / 7D")
        st.markdown(f"**{company}** · {r['sector']} · {r['industry']}")
        st.write(r["business_summary"])
        st.info(f"Monitor: {r['monitoring_theme']}")

        tech = technicals(fetch_intraday(c.ticker, period="1mo", interval="1h"))
        if not tech.empty:
            tech_tabs = st.tabs(["Interactive Price", "Technical Signals", "Fundamentals", "What changed?"])
            with tech_tabs[0]:
                fig = go.Figure()
                fig.add_trace(go.Scatter(x=tech["Datetime"], y=tech["close"], name="Close", mode="lines"))
                if tech["sma20"].notna().any():
                    fig.add_trace(go.Scatter(x=tech["Datetime"], y=tech["sma20"], name="SMA 20", mode="lines"))
                if tech["sma50"].notna().any():
                    fig.add_trace(go.Scatter(x=tech["Datetime"], y=tech["sma50"], name="SMA 50", mode="lines"))
                fig.update_layout(height=480, hovermode="x unified", title="1-month intraday / hourly trend")
                st.plotly_chart(fig, use_container_width=True)
            with tech_tabs[1]:
                last = tech.dropna(subset=["close"]).iloc[-1]
                a,b,c1,d = st.columns(4)
                a.metric("RSI 14", f"{last['rsi14']:.1f}" if pd.notna(last['rsi14']) else "—")
                b.metric("MACD", f"{last['macd']:.2f}" if pd.notna(last['macd']) else "—")
                c1.metric("SMA 20", f"₹{last['sma20']:,.2f}" if pd.notna(last['sma20']) else "—")
                d.metric("SMA 50", f"₹{last['sma50']:,.2f}" if pd.notna(last['sma50']) else "—")
                signal = "Bullish" if pd.notna(last["rsi14"]) and last["rsi14"] > 55 and pd.notna(last["sma20"]) and last["close"] > last["sma20"] else "Weak / watch" if pd.notna(last["rsi14"]) and last["rsi14"] < 45 else "Mixed"
                st.info(f"Technical read: **{signal}**. This is a descriptive signal, not an investment recommendation.")
            with tech_tabs[2]:
                a,b,c1,d = st.columns(4)
                a.metric("Revenue", money_ind(f.iloc[0]["revenue"]) if not f.empty else "—")
                b.metric("Revenue growth", pct(f.iloc[0]["revenue_growth_pct"]) if not f.empty else "—")
                c1.metric("Net margin", pct(f.iloc[0]["net_margin_pct"]) if not f.empty else "—")
                d.metric("ROE", pct(f.iloc[0]["roe_pct"]) if not f.empty else "—")
                if not f.empty:
                    st.dataframe(f[["as_of_date","fiscal_period","revenue","net_income","revenue_growth_pct","profit_growth_pct","net_margin_pct","debt_equity","roe_pct","source"]], use_container_width=True, hide_index=True)
            with tech_tabs[3]:
                for bullet in analysis_narrative(c, int(c.get("news_7d",0)), int(c.get("corroborated_7d",0))):
                    st.markdown(f"• {bullet}")
        else:
            st.info("Intraday history is not currently available for this ticker. Historical daily analytics remain available below.")
            fig = px.line(p, x="trade_date", y="close", title="Daily price history")
            st.plotly_chart(fig, use_container_width=True)

        if not nw.empty:
            st.subheader("Recent multi-source coverage")
            show = nw[["published_at","source","publisher","title","sentiment","event_type","coverage_count","corroboration","link"]].copy()
            st.dataframe(show, use_container_width=True, hide_index=True, column_config={"link": st.column_config.LinkColumn("Open")})
        st.markdown(f"**Issuer / primary research:** [{r['source_url']}]({r['source_url']})")

    with tabs[6]:
        sector = universe.groupby("sector", as_index=False).agg(
            companies=("ticker", "count"), avg_return_30d=("return_30d", "mean"), median_return_30d=("return_30d", "median"),
            avg_volatility_30d=("volatility_30d", "mean"), high_attention=("attention_flag", lambda s: (s == "HIGH").sum()),
            total_news_7d=("news_7d", "sum"), corroborated_news=("corroborated_7d", "sum")
        ).sort_values("avg_return_30d", ascending=False)
        st.dataframe(sector.round(2), use_container_width=True, hide_index=True)
        col1, col2 = st.columns(2)
        with col1:
            fig = px.bar(sector.sort_values("avg_return_30d"), x="avg_return_30d", y="sector", orientation="h", title="Average 30D return by sector")
            st.plotly_chart(fig, use_container_width=True)
        with col2:
            fig = px.scatter(sector, x="avg_volatility_30d", y="avg_return_30d", size="companies", color="sector", text="sector", title="Sector risk / return")
            fig.update_traces(textposition="top center")
            st.plotly_chart(fig, use_container_width=True)
        heat = universe.pivot_table(index="sector", values=["return_30d","volatility_30d","news_7d","attention_score"], aggfunc="mean").sort_values("attention_score", ascending=False)
        st.subheader("Sector heatmap")
        fig = px.imshow(heat, text_auto=".1f", aspect="auto", title="Sector operating / market signal heatmap")
        st.plotly_chart(fig, use_container_width=True)

    with tabs[7]:
        st.subheader("📰 Multi-source News Intelligence")
        st.caption("Headlines are discovery metadata. Similar stories are clustered so corroboration is visible rather than treating repeated copies as independent facts.")
        nw = news[news.ticker.isin(universe.ticker)].copy()
        if nw.empty:
            st.info("No stored headlines yet. Run the ETL with news enabled.")
        else:
            source_pick = st.multiselect("News sources", sorted(nw["source"].dropna().unique()), default=sorted(nw["source"].dropna().unique()))
            sentiment_pick = st.multiselect("Sentiment tag", sorted(nw["sentiment"].dropna().unique()), default=sorted(nw["sentiment"].dropna().unique()))
            event_pick = st.multiselect("Event type", sorted(nw["event_type"].dropna().unique()), default=sorted(nw["event_type"].dropna().unique()))
            nw = nw[nw["source"].isin(source_pick) & nw["sentiment"].isin(sentiment_pick) & nw["event_type"].isin(event_pick)]
            if "coverage_count" in nw.columns:
                corroborated = nw[nw["coverage_count"].fillna(1) >= 2].copy()
                st.metric("Corroborated headline records", len(corroborated))
            st.dataframe(nw[["published_at","company_name","source","publisher","title","sentiment","event_type","coverage_count","corroboration","link"]].head(150), use_container_width=True, hide_index=True, column_config={"link": st.column_config.LinkColumn("Open source")})
            source_counts = nw.groupby("source").size().reset_index(name="headlines").sort_values("headlines", ascending=False)
            st.plotly_chart(px.bar(source_counts, x="headlines", y="source", orientation="h", title="Headline coverage by source"), use_container_width=True)

    with tabs[8]:
        st.subheader("🔎 Source Verification Center")
        st.write("For a selected company, the dashboard compares the current Yahoo Finance quote with the public NSE quote endpoint when it is reachable. A mismatch is flagged for review instead of silently choosing one number.")
        ver_company = st.selectbox("Company to verify", universe["company_name"].tolist(), key="verify_company")
        vticker = companies.loc[companies["company_name"] == ver_company, "ticker"].iloc[0]
        if st.button("Verify quote across sources", type="primary"):
            with st.spinner("Checking independent market sources…"):
                vr = quote_verification(vticker)
            st.session_state[f"verification_{vticker}"] = vr
        vr = st.session_state.get(f"verification_{vticker}")
        if vr:
            if vr.get("verdict") == "ERROR":
                st.error(vr.get("error", "Verification failed"))
            else:
                y = vr.get("yahoo", {})
                n = vr.get("nse", {})
                a,b,c1 = st.columns(3)
                a.metric("Yahoo / yfinance", f"₹{y['price']:,.2f}" if y.get("price") is not None else "—")
                b.metric("NSE India", f"₹{n['price']:,.2f}" if n.get("price") is not None else "Unavailable")
                c1.metric("Verification", vr.get("verdict", "—"))
                if vr.get("difference_pct") is not None:
                    st.caption(f"Absolute difference: ₹{vr['difference']:.4f} ({vr['difference_pct']:.3f}%).")
                st.write({
                    "Yahoo status": y.get("status"),
                    "NSE status": n.get("status"),
                    "Yahoo timestamp": y.get("timestamp_utc"),
                    "NSE checked": n.get("timestamp_utc"),
                })
        st.divider()
        st.subheader("News source registry")
        registry = pd.DataFrame([{"Source": k, "Feed": v if "{query}" not in v else "Google News company search", "Role": "Independent headline discovery"} for k,v in NEWS_SOURCES.items()])
        st.dataframe(registry, use_container_width=True, hide_index=True)
        st.caption("News feeds are used as headline/URL discovery only. Article text is not copied into the dataset. Respect each publisher's RSS/terms and obtain a licence for commercial redistribution where required.")
        for source in NEWS_SOURCES:
            st.markdown(f'<span class="source-chip">{source}</span>', unsafe_allow_html=True)

    with tabs[9]:
        st.subheader("Operational data & SQL layer")
        st.dataframe(logs.head(15), use_container_width=True, hide_index=True)
        st.markdown("**Tables:** `company_master`, `price_daily`, `financial_snapshot`, `news_articles`, `etl_run_log`.")
        st.code("SELECT ticker, return_30d, volatility_30d, max_drawdown_90d\nFROM price_daily\nWHERE trade_date = (SELECT MAX(trade_date) FROM price_daily)\nORDER BY return_30d ASC;", language="sql")
        st.download_button("Download historical price data", prices.to_csv(index=False).encode("utf-8"), "price_daily.csv", "text/csv")
        st.download_button("Download financial snapshot", financials.to_csv(index=False).encode("utf-8"), "financial_snapshot.csv", "text/csv")
        st.download_button("Download news dataset", news.to_csv(index=False).encode("utf-8"), "news_articles.csv", "text/csv")

    st.markdown("---")
    st.caption("Live quote layer: Yahoo Finance / yfinance, with NSE public verification when reachable. Historical layer: scheduled GitHub ETL. News: multiple RSS sources + Google News discovery. Descriptive analytics only; not investment advice.")


if __name__ == "__main__":
    main()
